# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "06:00" # UTC
    allow:
      - dependency-type: "all"
    groups:
      # Named groups (specific packages get their own PRs)
      nextjs:
        patterns:
          - "next/*"
      react:
        patterns:
          - "react/*"
          - "react-dom/*"
      prisma:
        patterns:
          - "@prisma/*"
          - "prisma/*"
      types:
        patterns:
          - "@types/*"
      testing-library:
        patterns:
          - "@testing-library/*"
    cooldown:
      default-days: 7
