allowBuilds:
  "@parcel/watcher": true
  "@prisma/engines": true
  bcrypt: true
  prisma: true
  sharp: true
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
confirmModulesPurge: false
verifyDepsBeforeRun: false
overrides:
  deepmerge-ts: ">=8.0.2"
